<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
require_once __DIR__ . '/../includes/NorthIndianChart.php';
require_once __DIR__ . '/../includes/ShashtiamsaCalculator.php';
requireLogin();
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');
header('Pragma: no-cache');
$uid=current_user_id();
$profileId=(int)($_GET['profile_id']??0);
if($profileId<=0){$stmt=db()->prepare('SELECT id FROM birth_profiles WHERE user_id=? ORDER BY id DESC LIMIT 1');$stmt->bind_param('i',$uid);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();$stmt->close();$profileId=(int)($row['id']??0);}
$stmt=db()->prepare('SELECT id,profile_name,full_name,date_of_birth,time_of_birth,location_name,birth_place,timezone FROM birth_profiles WHERE id=? AND user_id=? LIMIT 1');$stmt->bind_param('ii',$profileId,$uid);$stmt->execute();$profile=$stmt->get_result()->fetch_assoc();$stmt->close();
$calculation=null;if($profile){$stmt=db()->prepare('SELECT id,lagna,rashi,planetary_data,chart_data,api_response FROM kundli_calculations WHERE birth_profile_id=? ORDER BY id DESC LIMIT 1');$stmt->bind_param('i',$profileId);$stmt->execute();$calculation=$stmt->get_result()->fetch_assoc();$stmt->close();}
if(!$profile||!$calculation){http_response_code(404);exit('Kundli not found. Generate a Kundli from your birth profile first.');}
$planetary=json_decode((string)$calculation['planetary_data'],true)?:[];$chartData=json_decode((string)$calculation['chart_data'],true)?:[];$apiResponse=json_decode((string)$calculation['api_response'],true)?:[];
$chartAscendant=is_array($chartData['ascendant']??null)?$chartData['ascendant']:null;
if(!d60HasLongitude($chartAscendant)){$apiAscendant=d60FindAscendantObject($apiResponse);if($apiAscendant!==null){$chartAscendant=$apiAscendant;$chartData['ascendant']=$apiAscendant;}}
if(!d60HasLongitude($chartAscendant)){$ascLocal=d60FindNumericByKey($apiResponse,['local_degree','degree_in_sign','sign_degree','degree']);if($ascLocal!==null&&$calculation['lagna']!==null)$chartData['ascendant']=['name'=>'Ascendant','rashi'=>(string)$calculation['lagna'],'local_degree'=>$ascLocal];}
$d60=(new ShashtiamsaCalculator())->calculate($planetary,$chartData,$calculation['lagna']!==null?(string)$calculation['lagna']:null);$houses=$d60['houses'];
function d60HasLongitude(mixed $v):bool{if(!is_array($v))return false;foreach(['global_degree','longitude','sidereal_longitude','absolute_degree','local_degree','degree_in_sign','sign_degree','degree'] as $k)if(isset($v[$k])&&is_numeric($v[$k]))return true;return false;}
function d60FindAscendantObject(mixed $v):?array{if(!is_array($v))return null;foreach($v as $k=>$c){if(strcasecmp((string)$k,'ascendant')===0){if(is_array($c)&&d60HasLongitude($c))return$c;if(is_numeric($c))return['name'=>'Ascendant','local_degree'=>(float)$c];}if(is_array($c)){if(isset($c['name'])&&is_string($c['name'])&&strcasecmp(trim($c['name']),'ascendant')===0&&d60HasLongitude($c))return$c;$f=d60FindAscendantObject($c);if($f!==null)return$f;}}return null;}
function d60FindNumericByKey(mixed $v,array $keys):?float{if(!is_array($v))return null;$wanted=array_map('strtolower',$keys);foreach($v as $k=>$c){if(in_array(strtolower((string)$k),$wanted,true)&&is_numeric($c))return(float)$c;if(is_array($c)){$f=d60FindNumericByKey($c,$keys);if($f!==null)return$f;}}return null;}
function d60Value(mixed $v):string{return$v===null||$v===''?'—':e(is_scalar($v)?(string)$v:json_encode($v,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));}
function d60Deg(float $degree):string{$d=floor($degree);$m=round(($degree-$d)*60);if($m>=60){$d++;$m=0;}return sprintf('%02d°%02d′',$d,$m);}
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>D60 Shashtiamsa Chart — ASTROPOP</title><link rel="stylesheet" href="<?=e(APP_BASE_PATH)?>/assets/css/app.css"></head><body><main class="app-shell"><header class="topbar"><a class="brand" href="<?=e(APP_BASE_PATH)?>/dashboard.php">✦ ASTROPOP</a><nav><a href="<?=e(APP_BASE_PATH)?>/kundli.php?profile_id=<?=$profileId?>">Kundli</a><a href="<?=e(APP_BASE_PATH)?>/d1-chart.php?profile_id=<?=$profileId?>">D1 Rashi</a><a href="<?=e(APP_BASE_PATH)?>/d30-chart.php?profile_id=<?=$profileId?>">D30 Trimsamsa</a><a href="<?=e(APP_BASE_PATH)?>/d40-chart.php?profile_id=<?=$profileId?>">D40 Khavedamsa</a><a href="<?=e(APP_BASE_PATH)?>/d45-chart.php?profile_id=<?=$profileId?>">D45 Akshavedamsa</a><a href="<?=e(APP_BASE_PATH)?>/d60-chart.php?profile_id=<?=$profileId?>">D60 Shashtiamsa</a><a href="<?=e(APP_BASE_PATH)?>/logout.php">Log out</a></nav></header><section class="content-wrap"><div class="section-heading"><p class="eyebrow">VEDIC ASTROLOGY · D60</p><h1>Shashtiamsa Chart</h1><p class="muted"><?=e((string)$profile['full_name'])?> · <?=e((string)($profile['location_name']?:$profile['birth_place']))?> · North Indian format</p></div>
<section class="card chart-card"><div class="row-between"><div><p class="eyebrow">SHASHTIAMSA KUNDALI</p><h2>Shashtiamsa Chart (D60)</h2></div><span class="pill pill-success">Calculated from D1 degrees</span></div><?=renderNorthIndianChart($houses,$d60['lagna'],'D60 · SHASHTIAMSA')?><p class="muted chart-note">Each Rashi is divided into sixty equal portions of 0°30′. D60 signs count forward from the natal sign; the sixty named Shashtiamsas run in order for odd signs and in reverse for even signs.</p></section>
<section class="grid-2"><article class="card"><p class="eyebrow">D60 BASICS</p><div class="detail-grid detail-grid-3"><div><span>D60 Lagna</span><strong><?=d60Value($d60['lagna'])?></strong></div><div><span>D1 Lagna</span><strong><?=d60Value($calculation['lagna'])?></strong></div><div><span>D1 Moon Rashi</span><strong><?=d60Value($calculation['rashi'])?></strong></div></div></article><article class="card"><p class="eyebrow">BIRTH DATA</p><div class="detail-grid detail-grid-3"><div><span>Date</span><strong><?=e((string)$profile['date_of_birth'])?></strong></div><div><span>Time</span><strong><?=e((string)$profile['time_of_birth'])?></strong></div><div><span>UTC</span><strong><?=d60Value($profile['timezone'])?></strong></div></div></article></section>
<section class="card"><div class="row-between"><div><p class="eyebrow">SHASHTIAMSA PLACEMENT</p><h2>Planetary D1 → D60</h2></div><div class="hero-actions"><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/d45-chart.php?profile_id=<?=$profileId?>">D45 Akshavedamsa</a><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/d30-chart.php?profile_id=<?=$profileId?>">D30 Trimsamsa</a></div></div><div class="table-wrap"><table><thead><tr><th>Planet</th><th>D1 Rashi</th><th>D1 Degree</th><th>Part</th><th>Band</th><th>D60 Rashi</th><th>House</th><th>Shashtiamsa Deity</th></tr></thead><tbody><?php foreach($d60['positions'] as $position):?><tr><td><strong><?=e((string)$position['name'])?></strong></td><td><?=d60Value($position['d1_sign'])?></td><td><?=d60Deg((float)$position['d1_degree'])?></td><td><?=((int)$position['part'])?></td><td><?=d60Value($position['band'])?></td><td><?=d60Value($position['d60_sign'])?></td><td><?=isset($position['house'])?(int)$position['house']:'—'?></td><td><?=d60Value($position['deity'])?></td></tr><?php endforeach;?></tbody></table></div></section></section></main></body></html>
