<?php
declare(strict_types=1);
require_once __DIR__ . '/../includes/bootstrap.php';
requireLogin();
$uid=current_user_id(); $success=flash('success');
$stmt=db()->prepare('SELECT name,email FROM users WHERE id=? LIMIT 1'); $stmt->bind_param('i',$uid); $stmt->execute(); $user=$stmt->get_result()->fetch_assoc(); $stmt->close();
$stmt=db()->prepare('SELECT id,profile_name,full_name,date_of_birth,time_of_birth,birth_place,location_name,latitude,longitude,timezone FROM birth_profiles WHERE user_id=? ORDER BY id DESC LIMIT 1'); $stmt->bind_param('i',$uid); $stmt->execute(); $profile=$stmt->get_result()->fetch_assoc(); $stmt->close();
$stmt=db()->prepare('SELECT id,birth_profile_id,created_at FROM kundli_calculations WHERE user_id=? ORDER BY id DESC LIMIT 1'); $stmt->bind_param('i',$uid); $stmt->execute(); $kundli=$stmt->get_result()->fetch_assoc(); $stmt->close();
$apiConfigured=VEDIC_API_KEY!=='';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard — ASTROPOP</title><link rel="stylesheet" href="<?=e(APP_BASE_PATH)?>/assets/css/app.css"></head><body><main class="app-shell"><header class="topbar"><a class="brand" href="<?=e(APP_BASE_PATH)?>/dashboard.php">✦ ASTROPOP</a><nav><a href="<?=e(APP_BASE_PATH)?>/birth/">Birth profile</a><?php if($profile): ?><a href="<?=e(APP_BASE_PATH)?>/kundli.php?profile_id=<?=(int)$profile['id']?>">Kundli</a><a href="<?=e(APP_BASE_PATH)?>/planetary-analysis.php?profile_id=<?=(int)$profile['id']?>">Analysis</a><a href="<?=e(APP_BASE_PATH)?>/yogas.php?profile_id=<?=(int)$profile['id']?>">Yogas</a><a href="<?=e(APP_BASE_PATH)?>/charts.php?profile_id=<?=(int)$profile['id']?>">Charts</a><?php endif; ?><a href="<?=e(APP_BASE_PATH)?>/logout.php">Log out</a></nav></header><section class="content-wrap"><div class="section-heading"><p class="eyebrow">ASTROPOP ASTROLOGY</p><h1>Good to see you, <?=e((string)($user['name']??'there'))?>.</h1><p class="muted">Accurate birth data first. Interpretation and timing next.</p></div><?php if($success): ?><div class="alert alert-success"><?=e($success)?></div><?php endif; ?>
<section class="grid-2"><article class="card"><p class="eyebrow">ACCOUNT</p><h2><?=e((string)($user['name']??''))?></h2><p class="muted"><?=e((string)($user['email']??''))?></p><span class="pill">Active account</span></article><article class="card"><p class="eyebrow">ASTROLOGY API</p><h2><?=$apiConfigured?'Configured':'Configuration pending'?></h2><p class="muted">Server-side VedicAstroAPI connection.</p><span class="pill <?=$apiConfigured?'pill-success':''?>"><?=$apiConfigured?'Ready':'Add VEDIC_API_KEY'?></span></article></section>
<section class="card"><div class="row-between"><div><p class="eyebrow">BIRTH PROFILE</p><h2><?=$profile?e((string)$profile['profile_name']):'Your Kundli starts here'?></h2></div><a class="button button-primary" href="<?=e(APP_BASE_PATH)?>/birth/"><?=$profile?'Manage profile':'Add birth details'?></a></div><?php if($profile): ?><div class="detail-grid"><div><span>Date</span><strong><?=e((string)$profile['date_of_birth'])?></strong></div><div><span>Time</span><strong><?=e((string)($profile['time_of_birth']??'Unknown'))?></strong></div><div><span>Place</span><strong><?=e((string)$profile['birth_place'])?></strong></div><div><span>Location</span><strong><?=$profile['latitude']!==null?e((string)$profile['latitude']).', '.e((string)$profile['longitude']):'Pending'?></strong></div></div><p class="muted">Location: <strong><?=e((string)($profile['location_name']??'Not resolved'))?></strong> · Kundli: <strong><?=$kundli?'Generated and cached':'Not generated yet'?></strong></p><div class="hero-actions"><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/api-debug.php?profile_id=<?=(int)$profile['id']?>">API debug</a><?php if($kundli): ?><a class="button button-primary" href="<?=e(APP_BASE_PATH)?>/kundli.php?profile_id=<?=(int)$profile['id']?>">Open Kundli</a><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/planetary-analysis.php?profile_id=<?=(int)$profile['id']?>">Planetary Analysis</a><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/yogas.php?profile_id=<?=(int)$profile['id']?>">Yoga Report</a><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/charts.php?profile_id=<?=(int)$profile['id']?>">Varga Charts</a><?php else: ?><a class="button button-primary" href="<?=e(APP_BASE_PATH)?>/birth/?profile_id=<?=(int)$profile['id']?>">Continue Kundli setup</a><?php endif; ?></div><?php else: ?><p class="muted">Add your birth details to generate a Kundli and unlock analysis.</p><?php endif; ?></section>
<?php if($kundli): ?><section class="grid-2"><article class="card"><p class="eyebrow">INTERPRETATION PIPELINE</p><h2>From chart to insight</h2><p class="muted">D1 and key Vargas → planetary facts → yoga detection → Vimshottari timing → topic-specific interpretation.</p><div class="hero-actions"><a class="button button-primary" href="<?=e(APP_BASE_PATH)?>/planetary-analysis.php?profile_id=<?=(int)$profile['id']?>">Start analysis</a><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/yogas.php?profile_id=<?=(int)$profile['id']?>">Review yogas</a></div></article><article class="card"><p class="eyebrow">ADVANCED</p><h2>Divisional charts</h2><p class="muted">Use D9, D10, D7 and other Vargas when a question requires them. The full catalogue stays behind the Charts hub.</p><div class="hero-actions"><a class="button button-secondary" href="<?=e(APP_BASE_PATH)?>/charts.php?profile_id=<?=(int)$profile['id']?>">Open Charts</a></div></article></section><?php endif; ?>
</section></main></body></html>
